In [1]:
import numpy as np
a=np.array( [ [ 1,2,3,4 ],[ 5,6,7,8 ] ] )
print (a)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
import numpy as np
a=np.array( [ [ 1,2,3,4 ],[ 5,6,7,8 ] ] )
print (a[0,1])

2


In [3]:
import numpy as np
a=np.array( [ [ 1,2,3,4 ]] )
print (a[0])


[1 2 3 4]


In [4]:
import numpy as np
a=np.array( [ [ 1,2,3,4 ],[ 5,6,7,8 ] ,[1,5,9,10]] )
print (a[2,0])

1


In [5]:
import numpy as np
a=np.array( [ [ 1,2,3,4 ],[ 5,6,7,8 ] ] )
print (a.shape)

(2, 4)
